services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      # Mount the project directory to the container
      - .:/app
      # Use an anonymous volume for node_modules to prevent it from being overwritten
      - /app/node_modules
    environment:
      # Enables hot-reloading in some environments
      - CHOKIDAR_USEPOLLING=true