services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./:/app
      - /app/node_modules
    command: npm run start-watch

  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    volumes:
      - ./:/app
      - /app/node_modules
    # Default command from Dockerfile.test is npm test
    