services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      # Enables hot-reloading in some environments
      - CHOKIDAR_USEPOLLING=true